/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: beae8b2d64328b9542358b1adc1f4ce1)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	SITE_URL: "https://example.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL">> {}
}
